export const simpsons = [
  {
    id: 1,
    age: 39,
    birthdate: '1956-05-12',
    description:
      'Homer Jay Simpson (born May 12, 1956) is a man from Springfield and the protagonist of the animated television series The Simpsons. He is a crude, ignorant, and slobbish individual, although he is fundamentally a good person and shows great caring and loyalty to his family, friends and on occasion, to those he barely knows or those he considers his enemies.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 1,
    gender: 'Male',
    name: 'Homer Simpson',
    occupation: 'Safety Inspector',
    phrases: [
      'Doh!',
      'Why you little...!',
      'Woo-hoo!',
      'Mmm... (food)... *drooling*',
      'Stupid Flanders!',
      'Shut up Flanders!',
      'AAAAGHH!',
      'Lisa, knock off that racket!',
      'Uh oh, the boss.',
      'Lets all go out for frosty chocolate milkshakes!',
      'Whatever, Ill be at Moes.',
      'I am evil Ho-mer! I am evil Ho-mer! I am evil Ho-mer!',
      'Better them than me.',
      'Better them than me... Oh wait, that was me.',
      'Marge, my face hurts again!',
    ],
    portrait_path: '/character/1.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 1,
      airdate: '1987-04-19',
      description:
        'Good Night is the first Simpsons short and the first televised appearance of the Simpson family. It originally aired on The Tracey Ullman Show on April 19, 1987. This short was also used before the couch gag in the episode "Looking for Mr. Goodbart" to celebrate three decades of the Simpsons\' televised debut, but only showed the scene with Marge singing "Rock-a-bye baby" to Maggie.',
      episode_number: 1,
      image_path: '/short/1.webp',
      name: 'Good Night',
      season: 1,
      synopsis:
        'Marge and Homer Simpson, a married couple, say goodnight to their three kids, Bart, Lisa, and Maggie Simpson but all does not go to plan. Bart philosophically contemplates (first time and last) the wonders of the mind, Lisa hears Marge say "don\'t let the bed bugs bite" and fears that her bed bugs will eat her, and Maggie is traumatized by the lyrics of "rock-a-bye-baby".',
    },
  },
  {
    id: 2,
    age: 39,
    birthdate: null,
    description:
      'Marjorie Jacqueline "Marge" Simpson (née Bouvier) (Born March 19) is the homemaker and matriarch of the Simpson family. She is also one of the five main characters in The Simpsons TV series. She and her husband Homer have three children: Bart, Lisa, and Maggie. Marge is the moralistic force in her family and often provides a raspy and grounding voice in the midst of her family\'s antics by trying to maintain order in the Simpson household. Aside from her duties at home, Marge has flirted briefly with a number of careers ranging from a police officer to an anti-violence activist.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 1,
    gender: 'Female',
    name: 'Marge Simpson',
    occupation: 'Unemployed',
    phrases: [
      'Hrmmm...',
      'Now its Marges time to shine!',
      'Oh!',
      'Oh, Homie!',
      'Its true. Women arent very good drivers.',
    ],
    portrait_path: '/character/2.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 1,
      airdate: '1987-04-19',
      description:
        'Good Night is the first Simpsons short and the first televised appearance of the Simpson family. It originally aired on The Tracey Ullman Show on April 19, 1987. This short was also used before the couch gag in the episode "Looking for Mr. Goodbart" to celebrate three decades of the Simpsons\' televised debut, but only showed the scene with Marge singing "Rock-a-bye baby" to Maggie.',
      episode_number: 1,
      image_path: '/short/1.webp',
      name: 'Good Night',
      season: 1,
      synopsis:
        'Marge and Homer Simpson, a married couple, say goodnight to their three kids, Bart, Lisa, and Maggie Simpson but all does not go to plan. Bart philosophically contemplates (first time and last) the wonders of the mind, Lisa hears Marge say "don\'t let the bed bugs bite" and fears that her bed bugs will eat her, and Maggie is traumatized by the lyrics of "rock-a-bye-baby".',
    },
  },
  {
    id: 3,
    age: 10,
    birthdate: '1980-02-23',
    description:
      'Bartholomew JoJo "Bart" Simpson (February 23, 1979) is the mischievous, rebellious, misunderstood, disruptive and "potentially dangerous" oldest child of the Simpson family in The Simpsons. He is the only son of Homer and Marge Simpson, and the older brother of Lisa and Maggie. He also has been nicknamed "Cosmo", after discovering a comet in "Bart\'s Comet". Bart has also been on the cover on numerous comics, such as "Critical Hit", "Simpsons Treasure Trove #11", and "Winter Wingding". Bart also has a 100-issue comic series entitled the Simpson Comics Presents Bart Simpson. Bart is loosely based off of Matt Groening (who\'s the creator of The Simpsons) and his older brother, Mark Groening.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 1,
    gender: 'Male',
    name: 'Bart Simpson',
    occupation: 'Student at Springfield Elementary School',
    phrases: [
      '¡Ay Caramba!',
      'Eat my shorts!',
      'I didnt do it!',
      'Dont have a cow, man.',
      'I’m Bart Simpson, who the hell are you?',
      'Aah! Sideshow Bob!',
      'Nobody better lay a finger on my Butterfinger!',
      'I didnt think it was physically possible, but this both sucks and blows.',
    ],
    portrait_path: '/character/3.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 1,
      airdate: '1987-04-19',
      description:
        'Good Night is the first Simpsons short and the first televised appearance of the Simpson family. It originally aired on The Tracey Ullman Show on April 19, 1987. This short was also used before the couch gag in the episode "Looking for Mr. Goodbart" to celebrate three decades of the Simpsons\' televised debut, but only showed the scene with Marge singing "Rock-a-bye baby" to Maggie.',
      episode_number: 1,
      image_path: '/short/1.webp',
      name: 'Good Night',
      season: 1,
      synopsis:
        'Marge and Homer Simpson, a married couple, say goodnight to their three kids, Bart, Lisa, and Maggie Simpson but all does not go to plan. Bart philosophically contemplates (first time and last) the wonders of the mind, Lisa hears Marge say "don\'t let the bed bugs bite" and fears that her bed bugs will eat her, and Maggie is traumatized by the lyrics of "rock-a-bye-baby".',
    },
  },
  {
    id: 4,
    age: 8,
    birthdate: '1982-05-09',
    description:
      'Lisa Marie Simpson is the elder daughter and middle child of the Simpson family and one of the two tritagonists (along with Marge,) of The Simpsons. She was named after a train called Lil\' Lisa on her parents\' 1st anniversary. In "Homer and Lisa Exchange Cross Words", she called herself Lisa Bouvier after estranging herself from her father after he bet against her in a crossword tournament.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 1,
    gender: 'Female',
    name: 'Lisa Simpson',
    occupation: 'Student at Springfield Elementary School, CTU Agent, Hall-monitor, Member of PETA',
    phrases: [
      'Well, I wish you wouldnt. Because, aside from the fact that he has the same frailties as all human beings, hes the only father I have. Therefore, he is my model of manhood, and my estimation of him will govern the prospects of my adult relationships. So I hope you bear in mind that any knock at him is a knock at me. And I am far too young to defend myself against such onslaughts.',
      'Bart!',
      'If anyone wants me, Ill be in my room.',
      'Quit it, Bart!',
      'BAAAAART!!',
      'Mommy.',
      'David Hasselhoff.',
      'Homer.',
      'Having never received encouragement, Im not sure how it should sound, but here goes: I believe in you.',
      'Shut up, Meg.',
      'The truth must be told.',
      'I hope these are recyclable.',
      'Yeah, Bart!',
    ],
    portrait_path: '/character/4.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 1,
      airdate: '1987-04-19',
      description:
        'Good Night is the first Simpsons short and the first televised appearance of the Simpson family. It originally aired on The Tracey Ullman Show on April 19, 1987. This short was also used before the couch gag in the episode "Looking for Mr. Goodbart" to celebrate three decades of the Simpsons\' televised debut, but only showed the scene with Marge singing "Rock-a-bye baby" to Maggie.',
      episode_number: 1,
      image_path: '/short/1.webp',
      name: 'Good Night',
      season: 1,
      synopsis:
        'Marge and Homer Simpson, a married couple, say goodnight to their three kids, Bart, Lisa, and Maggie Simpson but all does not go to plan. Bart philosophically contemplates (first time and last) the wonders of the mind, Lisa hears Marge say "don\'t let the bed bugs bite" and fears that her bed bugs will eat her, and Maggie is traumatized by the lyrics of "rock-a-bye-baby".',
    },
  },
  {
    id: 5,
    age: 1,
    birthdate: '1990-11-07',
    description:
      'Margaret Lenny "Maggie" Simpson is the one-year-old daughter and youngest child of Marge and Homer Simpson, the baby sister to Bart and Lisa Simpson and one of the five main characters of The Simpsons. She is often seen sucking on her pacifier, and when she walks, she usually trips over her clothing and falls on her face. Because she rarely ever talks, Maggie is the least seen and heard in the Simpson family. Maggie is very young, at the infant age of only 1.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 1,
    gender: 'Female',
    name: 'Maggie Simpson',
    occupation: 'Unknown',
    phrases: ['*suck-suck*', 'Good night.', 'Daddy.'],
    portrait_path: '/character/5.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 1,
      airdate: '1987-04-19',
      description:
        'Good Night is the first Simpsons short and the first televised appearance of the Simpson family. It originally aired on The Tracey Ullman Show on April 19, 1987. This short was also used before the couch gag in the episode "Looking for Mr. Goodbart" to celebrate three decades of the Simpsons\' televised debut, but only showed the scene with Marge singing "Rock-a-bye baby" to Maggie.',
      episode_number: 1,
      image_path: '/short/1.webp',
      name: 'Good Night',
      season: 1,
      synopsis:
        'Marge and Homer Simpson, a married couple, say goodnight to their three kids, Bart, Lisa, and Maggie Simpson but all does not go to plan. Bart philosophically contemplates (first time and last) the wonders of the mind, Lisa hears Marge say "don\'t let the bed bugs bite" and fears that her bed bugs will eat her, and Maggie is traumatized by the lyrics of "rock-a-bye-baby".',
    },
  },
  {
    id: 6,
    age: null,
    birthdate: null,
    description:
      'Abraham Jebediah "Abe" Simpson II, commonly known as Grampa Simpson or simply Grampa, is a major recurring character in The Simpsons and a supporting character in The Simpsons Movie. He is the oldest patriarch of the Simpson family, husband of Rita LaFleur, ex-husband of the late Mona Simpson, father of Homer Simpson, Herbert Powell, and Abbey, father-in-law of Marge Simpson and paternal grandfather of Bart, Lisa, and Maggie Simpson. He is also the ex-boyfriend of Jacqueline Bouvier.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: 19,
    gender: 'Male',
    name: 'Abe Simpson II',
    occupation: 'Retired',
    phrases: [
      'Ahh!',
      'Im Santa? Oh, now Ill never die!',
      'Hi, David, Im Grampa!',
      'They pay me $800 a week to tell a cat and mouse what to do!',
    ],
    portrait_path: '/character/6.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: {
      id: 19,
      airdate: '1988-01-10',
      description:
        'Grandpa and the Kids is the nineteenth Simpsons short and originally aired on The Tracey Ullman Show on January 10, 1988.',
      episode_number: 19,
      image_path: '/short/19.webp',
      name: 'Grandpa and the Kids',
      season: 2,
      synopsis:
        'Grandpa tells the kids stories such as times when he was their age. They eventually stop paying attention to him and he tries to regain their attention by faking his death.',
    },
  },
  {
    id: 7,
    age: null,
    birthdate: null,
    description:
      'Patricia Maleficent "Patty" Bouvier is one of Marge\'s cynical chain-smoking twin sisters, who works at the DMV and has a strong dislike for her brother-in-law, Homer Simpson. Patty is a lesbian since she has confessed this to Marge (asking "did you actually think I was straight?") and appeared on a float at a pride parade. She is also the maternal aunt to Bart, Lisa, Maggie, and Ling. She is named after Matt Groening\'s sister Patty Groening.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Female',
    name: 'Patty Bouvier',
    occupation: 'Springfield DMV Employee',
    phrases: [
      'Some days at the DMV, we dont let the line move at all. We call those weekdays.',
      'Hell no! I like girls!',
    ],
    portrait_path: '/character/7.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 8,
    age: null,
    birthdate: null,
    description:
      "Selma Bouvier-D'Amico (née Bouvier; previously Terwilliger, Hutz, McClure, Discothèque, and Simpson) is one of Marge's older chain-smoking twin sisters. She works at the DMV and possesses a strong dislike for her brother-in-law, Homer, although on extremely rare occasions she shows kindness towards him and seems to tolerate him. She seems to despise Homer slightly less than her twin sister, Patty Bouvier.",
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Female',
    name: 'Selma Bouvier',
    occupation: 'Employee of Department of Motor Vehicles',
    phrases: ['Hows my blubber in-law?', 'Drivers License is on me!'],
    portrait_path: '/character/8.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 9,
    age: 60,
    birthdate: null,
    description:
      "Nedward \"Ned\" Flanders, Jr., more commonly known as Flanders, is the Simpson family's extremely religious next door neighbor. He is a genuinely well-meaning, good-natured person. Though firmly religious, he can be timid and something of an easy pushover. He is a major character in The Simpsons and a minor, recurring antagonist in the Treehouse of Horror episodes. Ned thoroughly worships God and strictly follows the Bible as literally as possible and is easily shocked when challenged on any point of dogma. He owns Leftorium Express, a downsized version of his former business The Leftorium and a home business, Flancrest Enterprises, which makes religious hook rugs. He also works as a member of the Springfield Volunteer Fire Department. He even (legally) owns the Simpsons' house, renting it out to the family at a low rate, showing that he would burn through much of his resources just to help his neighbors out. In Hurricane Neddy, Flanders was shown to be a kid 30 years ago in the show's floating timeline, but in Viva Ned Flanders, he claims to be 60 years old and looks younger thanks to following the 3 C's.",
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Ned Flanders',
    occupation: 'The Leftorium (formerly)',
    phrases: ['Howdily-doodily, neighborino!', 'Hi-diddly-ho!'],
    portrait_path: '/character/9.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 10,
    age: null,
    birthdate: null,
    description:
      'Maude Flanders was a major character of The Simpsons in the first 11 seasons, was the first wife of Ned Flanders, and the late mother of Todd and Rod Flanders.',
    first_appearance_ep_id: 19,
    first_appearance_sh_id: null,
    gender: 'Female',
    name: 'Maude Flanders',
    occupation: 'Housewife (former)',
    phrases: [
      'I dont judge Homer or Marge. Thats for vengeful God to do.',
      'Neddy doesnt believe in insurance. He considers it a form of gambling.',
      'I know. They make you uncomfortable.',
      'In many ways, Maude Flanders was a supporting player in our lives. She didnt grab our attention with memorable catchphrases, or comical accents. But, whether you noticed her or not, Maude was always there but then she was still alive in episode 6',
      'Excuse me, Edna. I dont think were talking about love here. Were talking about S-E-X in front of the C-H-I-L-D-R-E-N.',
    ],
    portrait_path: '/character/10.webp',
    status: 'Deceased',
    first_appearance_ep: {
      id: 19,
      airdate: '1990-11-15',
      description:
        "Dead Putting Society is the sixth episode of Season 2, and the show's 19th episode overall.",
      episode_number: 19,
      image_path: '/episode/19.webp',
      name: 'Dead Putting Society',
      season: 2,
      synopsis:
        "After feeling that his goody-two-shoes neighbor, Ned Flanders, is better than him in every way, Homer decides to prove his family's worth...by forcing Bart to compete in a mini-golf tournament with Ned's son, Todd.",
    },
    first_appearance_sh: null,
  },
  {
    id: 11,
    age: null,
    birthdate: null,
    description:
      'Rodney "Rod" Flanders is the oldest son of Ned Flanders and Maude Flanders and a stepson to Edna Krabappel. He has curly hair, light blue polo shirt, dark blue pants and gray shoes.',
    first_appearance_ep_id: 7,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Rod Flanders',
    occupation: 'Student at Springfield Elementary School',
    phrases: ['Yay!!', 'What does gay mean??'],
    portrait_path: '/character/11.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 7,
      airdate: '1990-02-18',
      description:
        '"The Call of the Simpsons" is the seventh episode of Season 1. It was planned to be the ninth episode of the first season in production order, but became the seventh in broadcasting order.',
      episode_number: 7,
      image_path: '/episode/7.webp',
      name: 'The Call of the Simpsons',
      season: 1,
      synopsis:
        'The Simpsons go on vacation in a rickety RV — and end up lost in the woods when the RV goes over a cliff.',
    },
    first_appearance_sh: null,
  },
  {
    id: 12,
    age: null,
    birthdate: null,
    description:
      'Todd Homer Flanders is the youngest son of Ned and Maude Flanders and a stepson to Edna Krabappel. He is the most impressionable and youngest member of the Flanders family. He wears brown shoes, bluish-green shorts, a pink polo shirt and sports the "Devil\'s Curly Hair".',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Todd Flanders',
    occupation:
      'Student at Springfield Elementary SchoolStudent at a religious private school (formerly)',
    phrases: ['I said I dont want any damn vegetables!'],
    portrait_path: '/character/12.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 13,
    age: 1381,
    birthdate: '1886-09-15',
    description:
      "Charles Montgomery Plantagenet Schicklgruber Burns, also known as Monty Burns, Montgomery Burns, C.M. Burns, and Mr. Burns, is the owner of the Springfield Nuclear Power Plant in The Simpsons franchise. He is Springfield's richest, oldest (supposedly), most powerful, and undoubtedly greediest and meanest citizen. His net worth has been stated to be in the billions and in one instance was pegged at exactly $1,800,037,022.",
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Charles Montgomery Burns',
    occupation: 'Owner & Director of the Springfield Nuclear Power Plant',
    phrases: [
      'Excellent!',
      'Release the hounds!',
      'Smithers!',
      'Smithers, who is this ?',
      'Simpson, eh?',
      'Youre fired!',
      'Oh, Fiddlesticks!',
    ],
    portrait_path: '/character/13.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 14,
    age: null,
    birthdate: null,
    description:
      'Waylon Joseph Smithers, Jr., better known as Mr. Smithers, Waylon Smithers or simply Smithers, (born December 25) is a recurring character on The Simpsons. He is also a minor character in The Simpsons Movie.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Waylon Smithers, Jr.',
    occupation: 'Assistant to Mr. Burns',
    phrases: [
      'Yes, sir?',
      'Thats Homer Simpson, sir - one of your [put-down]s from Sector 7G.',
      'Actually, I value every second were together: from the moment I squeeze his orange juice in the morning, till I... tuck him in at night. Hes not just my boss, hes my best friend, too.',
      'All right, thats it. You know, I used to wonder why Mr. Burns hated humanity. Now I know. You open your heart and they mock your very decency.',
    ],
    portrait_path: '/character/14.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 15,
    age: null,
    birthdate: null,
    description:
      "Sir Herschel Shmoikel Pinchas Yerucham Krustofsky, also once known under the alias of Rory B. Bellows, better known by his stage name Krusty the Clown (sometimes spelled as: Krusty the Klown), is the cynical, burnt-out, addiction-riddled smoking clown host of Bart, Lisa, and Maggie's favorite TV show The Krusty the Clown Show. He is a recurring character in The Simpsons and has a supporting role in The Simpsons Movie.",
    first_appearance_ep_id: 12,
    first_appearance_sh_id: 35,
    gender: 'Male',
    name: 'Krusty the Clown',
    occupation: 'Television personality',
    phrases: [
      'Hey hey, kids!',
      'Hoohoohoohahaha!',
      'Why you little!',
      'Im Krusty The Clown! And I Love you!',
    ],
    portrait_path: '/character/15.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 12,
      airdate: '1990-04-29',
      description:
        '"Krusty Gets Busted" is the twelfth episode of Season 1. Kent Brockman, Judge Roy Snyder and Scott Christian make their first appearances in this episode. Kelsey Grammer makes his debut as Sideshow Bob.',
      episode_number: 12,
      image_path: '/episode/12.webp',
      name: 'Krusty Gets Busted',
      season: 1,
      synopsis:
        "Bart and Lisa play amateur sleuth for their hero, Krusty the Clown, after he's accused of robbing the Kwik-E-Mart and Homer implicates him in the crime.",
    },
    first_appearance_sh: {
      id: 35,
      airdate: '1989-01-15',
      description:
        'The Krusty the Clown Show is the thirty-fifth Simpsons short and originally aired on The Tracey Ullman Show on January 15, 1989.',
      episode_number: 35,
      image_path: '/short/35.webp',
      name: 'The Krusty the Clown Show',
      season: 3,
      synopsis:
        'The kids get to watch The Krusty the Clown Show live although Bart suspects that Krusty is an imposter and exposes him.',
    },
  },
  {
    id: 16,
    age: null,
    birthdate: null,
    description:
      'Moammar Morris "Moe" Szyslak (pronounced /ˈsɪzlæk/ or "siz-lack"), also known as Moe the Bartender is the proprietor and bartender of "Moe\'s Tavern", a Springfield bar frequented by Homer and his friends. He has once stated that he moved to Springfield from the Netherlands. He also owns Moe\'s Bagels in Colorado and Moe\'s Express in the Food Court area of the Springfield Mall.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Moe Szyslak',
    occupation: "Bartender and Owner of Moe's Tavern",
    phrases: [
      'How ya doing?',
      'Whaaaaaaat?',
      'Whats-a-matter, Homer?',
      'When I get a hold of you, Ill (insert threat here)',
      'Hi ya, Midge.',
      'Mike Rotch',
      'Im a stupid moron with an ugly  face, and a big butt, and my butt smells, and I like to kiss my own butt.',
    ],
    portrait_path: '/character/16.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 17,
    age: 47,
    birthdate: null,
    description:
      'Apu Nahasapeemapetilon, Jr., also known as Apu Du Beaumarchais, Slime Q. Slimedog and Steve Barnes, is the operator of the Kwik-E-Mart. He is a recurring character in The Simpsons. He is an immigrant from India, and as such, speaks with a strong Indian accent. Accounts disagree as to whether he is a college dropout or if he has a PhD.',
    first_appearance_ep_id: 8,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Apu Nahasapeemapetilon',
    occupation: 'Owner of the Kwik-E-Mart',
    phrases: [
      'Thank you! Come again.',
      'That is a great dishonor to my ancestors and my God, but okay.',
      'Okay, whatever.',
      'Alright.',
      'I cant believe you dont shut up!',
      '(Referring to Homer) He slept, he stole, he was rude to the customers. Still, there goes the best-damned employee a convenience store ever had.',
    ],
    portrait_path: '/character/17.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 8,
      airdate: '',
      description:
        'The Telltale Head is the eighth episode of Season 1. It was planned to be the seventh episode of the season. This is the first episode of the series in which Sideshow Bob, Reverend Timothy Lovejoy, Jimbo Jones, Kearney Zzyzwicz, Dolph Starbeam, Ms. Albright, and Apu Nahasapeemapetilon appear for the first time. This was also the first appearance of Krusty the Clown (if not counting the Ullman short The Krusty the Clown Show).',
      episode_number: 8,
      image_path: '/episode/8.webp',
      name: 'The Telltale Head',
      season: 1,
      synopsis:
        'While cornered by the entire town, Bart tells the story of how he cut off the head of the Jebediah Springfield statue to impress local thugs, Dolph, Jimbo Jones, and Kearney.',
    },
    first_appearance_sh: null,
  },
  {
    id: 18,
    age: 57,
    birthdate: '1953-07-08',
    description:
      'Walter Seymour Skinner or Seymour  Skinner (real name: Armin Tamzarian) is a recurring character in The Simpsons. He is the principal of Springfield Elementary School, and a stereotypical educational bureaucrat. He struggles to control the crumbling school and is constantly engaged in a battle against its inadequate resources, apathetic and bitter teachers, and often rowdy and unenthusiastic students, Bart Simpson being a standout example. A strict disciplinarian, Skinner has an uptight, militaristic attitude that stems from his years in the United States Army as a Green Beret, which included service in the Vietnam War, where he achieved the rank of a sergeant, according to his rank insignia. As a result of his service in the Vietnam War, he is often plagued by horrible memories of his involvement via post-traumatic stress disorder, sometimes even happening at the most inopportune of times. It is also implied that he received a severe injury during the Vietnam War on his posterior to require a metal plate to be installed in it.',
    first_appearance_ep_id: 1,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Seymour Skinner',
    occupation: 'Principal of Springfield Elementary School',
    phrases: [],
    portrait_path: '/character/18.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 1,
      airdate: '1989-12-17',
      description:
        '"Simpsons Roasting on an Open Fire" (also known as "The Simpsons Christmas Special") is the first episode of Season 1 of The Simpsons, as well as the series premiere/pilot episode of the series. It is the show\'s only episode to be aired in the 1980s. (Minus the original shorts.)',
      episode_number: 1,
      image_path: '/episode/1.webp',
      name: 'Simpsons Roasting on an Open Fire',
      season: 1,
      synopsis:
        'When Mr. Burns announces that none of the workers will be getting Christmas bonuses and Marge reveals that she spent the extra Christmas gift money on getting Bart\'s "Mother" tattoo removed, Homer keeps his lack of funds for the holidays a secret and gets a job as a mall Santa.',
    },
    first_appearance_sh: null,
  },
  {
    id: 19,
    age: null,
    birthdate: '1945-03-31',
    description:
      'Garibaldi "Gary" Chalmers III, better known as Superintendent Chalmers, is the superintendent of the Springfield Unified School District, which includes Springfield Elementary alongside either seven or 13 other schools.',
    first_appearance_ep_id: 79,
    first_appearance_sh_id: null,
    gender: 'Male',
    name: 'Gary Chalmers',
    occupation: 'Superintendent of Springfield Elementary School',
    phrases: [
      'SKINNERRRRRR!',
      'Aurora Borealis? At this time of year, at this time of day, in this part of the country, localized ENTIRELY within your kitchen..?',
    ],
    portrait_path: '/character/19.webp',
    status: 'Alive',
    first_appearance_ep: {
      id: 79,
      airdate: '1993-04-29',
      description: '"Whacking Day" is the 20th episode of Season 4.',
      episode_number: 79,
      image_path: '/episode/79.webp',
      name: 'Whacking Day',
      season: 4,
      synopsis:
        "Bart's latest stunt (driving Groundskeeper Willie's tractor into Superintendent Chalmers' posterior) lands him an explusion from Springfield Elementary. When moving to a private religious school doesn't help, Marge decides to home-school her son. Meanwhile, Lisa protests a local holiday where snakes get chased into the middle of town and whacked to death and enlists the help of Barry White (and Bart) to help the snakes escape abuse.",
    },
    first_appearance_sh: null,
  },
  {
    id: 20,
    age: null,
    birthdate: null,
    description:
      'Edna Krabappel was a recurring character and a fourth grade teacher at Springfield Elementary School up until her unspecified death in 2013.',
    first_appearance_ep_id: 2,
    first_appearance_sh_id: null,
    gender: 'Female',
    name: 'Edna Krabappel',
    occupation: 'Fourth grade teacher at Springfield Elementary School (formerly)',
    phrases: [
      'Ha!',
      'These tests will have no effect on your grades. They merely determine your future social status and financial success. If any.',
      'Do what I mean, not what I say.',
      'No matter what youve done, I always thought there was a spark of decency in you, Bart Simpson, but I was wrong. I never thought Id say this to a child, but you are bad on the inside.',
      'Remember: if you can teach one kid one thing, then today will be a success...',
    ],
    portrait_path: '/character/20.webp',
    status: 'Deceased',
    first_appearance_ep: {
      id: 2,
      airdate: '',
      description: '"Bart the Genius" is the second episode of Season 1.',
      episode_number: 2,
      image_path: '/episode/2.webp',
      name: 'Bart the Genius',
      season: 1,
      synopsis:
        "To get back at class nerd/teacher's pet, Martin Prince, for ratting him out to Principal Skinner for vandalism on school property, Bart switches his own intelligence test with Martin's. During a parent/principal conference about the defaced wall, the school counselor, Dr. Pryor, announces that Bart is a genius and only acts out because public school isn't stimulating enough, so Bart is sent to a school for genius kids — and finds out just how painfully below average he is.",
    },
    first_appearance_sh: null,
  },
]
